
netty:
  server:
    enabled: false
    port: 8888
    my-config:
      max-frame-length: 1024
      length-field-offset: 6
      length-field-length: 4
    http-config:
      max-content-length: 10240
  client:
    enabled: true
    address: 127.0.0.1
    port: 8888
    heart:
      write-time: 5
    coding-type: my_config
    my-config:
      max-frame-length: 1024
      length-field-offset: 6
      length-field-length: 4

server:
  port: 8081